# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2deef36fb5dc51ef023b0e7b175aab2ac50ecabf1fbfb5682e641464709f511d93057aaee9bfe3abbd112dbfa6c25ef12e863fe80fdfdda55fc3ac1bccad08a2

test:
  secret_key_base: 270010f0be3dd9be75d13eb1e4708ed13f8f9a35914514a48c1c660516dc167061bb58f1d31681fbc2bcb063d44934274505e9546a1cbc6a4d3f7d1fa93135ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
